# -*- coding: utf-8 -*-
"""tds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_nWmc7FDCCXwsJ_1gK83n3xjjJqWkzHx
"""

import streamlit as st

def find_largest(num1, num2, num3):
    """
    Function to find the largest among 3 numbers
    """
    largest = num1
    if num2 > largest:
        largest = num2
    if num3 > largest:
        largest = num3
    return largest

# Title of the app
st.title("Find the largest among the 3 given numbers")

# Input fields for the 3 numbers
num1 = st.number_input("Enter the first number", value=0, step=1)
num2 = st.number_input("Enter the second number", value=0, step=1)
num3 = st.number_input("Enter the third number", value=0, step=1)

# Find the largest number
largest_num = find_largest(num1, num2, num3)

# Display the largest number
st.write(f"The largest number is {largest_num}")